services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: psycalldb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./psycall_prod_dump.sql:/docker-entrypoint-initdb.d/psycall_prod_dump.sql:ro

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    command: bash -lc "sleep 10 && dotnet restore && dotnet watch run --urls=http://0.0.0.0:5109"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      BACKEND_PORT: "5109"
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=psycalldb;User=root;Password=root;"
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj
    ports:
      - "5109:5109"
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: "http://localhost:5109"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  db_data:
