// <auto-generated />
using System;
using MedicalDemo.Models;
using MedicalDemo.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalDemo.Migrations
{
    [DbContext(typeof(MedicalContext))]
    [Migration("20260125234140_ScheduleStatusToEnum")]
    partial class ScheduleStatusToEnum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("MedicalDemo.Models.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("admin_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_num");

                    b.HasKey("AdminId");

                    b.HasIndex(new[] { "AdminId" }, "admin_id_UNIQUE")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Announcement", b =>
                {
                    b.Property<byte[]>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("announcement_id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("message");

                    b.HasKey("AnnouncementId");

                    b.HasIndex(new[] { "AnnouncementId" }, "announcement_id_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "AuthorId" }, "author_id_idx");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Blackout", b =>
                {
                    b.Property<byte[]>("BlackoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("blackout_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.HasKey("BlackoutId");

                    b.HasIndex(new[] { "BlackoutId" }, "blackout_id_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "ResidentId" }, "resident_id_blackouts_idx");

                    b.ToTable("blackouts", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Date", b =>
                {
                    b.Property<byte[]>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("date_id");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("call_type");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("hours");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<byte[]>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("schedule_id");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("DateId");

                    b.HasIndex(new[] { "ResidentId" }, "resident_id_dates_idx");

                    b.HasIndex(new[] { "ScheduleId" }, "schedule_id");

                    b.HasIndex(new[] { "DateId" }, "schedule_id_UNIQUE")
                        .IsUnique();

                    b.ToTable("dates", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Invitation", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("datetime")
                        .HasColumnName("expires");

                    b.Property<string>("ResidentId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resident_id");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("used")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Token")
                        .HasName("PRIMARY");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Resident", b =>
                {
                    b.Property<string>("ResidentId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<int>("BiYearlyHours")
                        .HasColumnType("int")
                        .HasColumnName("bi_yearly_hours");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("first_name");

                    b.Property<int>("GraduateYr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("graduate_yr")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("HospitalRoleProfile")
                        .HasColumnType("int")
                        .HasColumnName("hospital_role_profile");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password")
                        .HasDefaultValueSql("''");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_num")
                        .HasDefaultValueSql("''");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int")
                        .HasColumnName("total_hours");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("int")
                        .HasColumnName("weekly_hours");

                    b.HasKey("ResidentId");

                    b.HasIndex(new[] { "Email" }, "email_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "ResidentId" }, "resident_id_UNIQUE")
                        .IsUnique();

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Rotation", b =>
                {
                    b.Property<byte[]>("RotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("rotation_id");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("month");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<string>("Rotation1")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("rotation");

                    b.HasKey("RotationId");

                    b.HasIndex(new[] { "ResidentId" }, "resident_id_rotation_idx");

                    b.HasIndex(new[] { "RotationId" }, "rotation_id_UNIQUE")
                        .IsUnique();

                    b.ToTable("rotations", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Schedule", b =>
                {
                    b.Property<byte[]>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("schedule_id");

                    b.Property<int>("GeneratedYear")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ScheduleId");

                    b.HasIndex(new[] { "ScheduleId" }, "schedule_id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("schedule_id_UNIQUE1");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.SwapRequest", b =>
                {
                    b.Property<byte[]>("IdswapRequests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("idswap_requests");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Details")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("details");

                    b.Property<DateOnly>("RequesteeDate")
                        .HasColumnType("date")
                        .HasColumnName("requestee_date");

                    b.Property<string>("RequesteeId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("requestee_id");

                    b.Property<DateOnly>("RequesterDate")
                        .HasColumnType("date")
                        .HasColumnName("requester_date");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("requester_id");

                    b.Property<byte[]>("ScheduleSwapId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("schedule_swap_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdswapRequests")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdswapRequests" }, "idswap_requests_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "RequesteeId" }, "requestee_id_idx");

                    b.HasIndex(new[] { "RequesterId" }, "requester_id_idx");

                    b.HasIndex(new[] { "ScheduleSwapId" }, "schedule_id_idx");

                    b.ToTable("swap_requests", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Vacation", b =>
                {
                    b.Property<byte[]>("VacationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("vacation_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Details")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("details");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("groupId");

                    b.Property<string>("HalfDay")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("half_day")
                        .IsFixedLength();

                    b.Property<string>("Reason")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("reason");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.HasKey("VacationId");

                    b.HasIndex(new[] { "ResidentId" }, "idx_resident_id");

                    b.ToTable("vacations", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Announcement", b =>
                {
                    b.HasOne("MedicalDemo.Models.Admin", "Author")
                        .WithMany("Announcements")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MedicalDemo.Models.Blackout", b =>
                {
                    b.HasOne("MedicalDemo.Models.Resident", "Resident")
                        .WithMany("Blackouts")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resident_id_blackouts");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("MedicalDemo.Models.Date", b =>
                {
                    b.HasOne("MedicalDemo.Models.Resident", "Resident")
                        .WithMany("Dates")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resident_id_dates");

                    b.HasOne("MedicalDemo.Models.Schedule", "Schedule")
                        .WithMany("Dates")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("schedule_id");

                    b.Navigation("Resident");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MedicalDemo.Models.Rotation", b =>
                {
                    b.HasOne("MedicalDemo.Models.Resident", "Resident")
                        .WithMany("Rotations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resident_id_rotation");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("MedicalDemo.Models.SwapRequest", b =>
                {
                    b.HasOne("MedicalDemo.Models.Resident", "Requestee")
                        .WithMany("SwapRequestRequestees")
                        .HasForeignKey("RequesteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("requestee_id");

                    b.HasOne("MedicalDemo.Models.Resident", "Requester")
                        .WithMany("SwapRequestRequesters")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("requester_id");

                    b.HasOne("MedicalDemo.Models.Schedule", "ScheduleSwap")
                        .WithMany("SwapRequests")
                        .HasForeignKey("ScheduleSwapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("schedule_swap_id");

                    b.Navigation("Requestee");

                    b.Navigation("Requester");

                    b.Navigation("ScheduleSwap");
                });

            modelBuilder.Entity("MedicalDemo.Models.Admin", b =>
                {
                    b.Navigation("Announcements");
                });

            modelBuilder.Entity("MedicalDemo.Models.Resident", b =>
                {
                    b.Navigation("Blackouts");

                    b.Navigation("Dates");

                    b.Navigation("Rotations");

                    b.Navigation("SwapRequestRequestees");

                    b.Navigation("SwapRequestRequesters");
                });

            modelBuilder.Entity("MedicalDemo.Models.Schedule", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("SwapRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
