// <auto-generated />
using System;
using MedicalDemo.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalDemo.Migrations
{
    [DbContext(typeof(MedicalContext))]
    [Migration("20260213015040_AddPGY4RotationScheduleTable")]
    partial class AddPGY4RotationScheduleTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("MedicalDemo.Models.Entities.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("admin_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_num");

                    b.HasKey("AdminId");

                    b.HasIndex(new[] { "AdminId" }, "admin_id_UNIQUE")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Announcement", b =>
                {
                    b.Property<byte[]>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("announcement_id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("message");

                    b.HasKey("AnnouncementId");

                    b.HasIndex(new[] { "AnnouncementId" }, "announcement_id_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "AuthorId" }, "author_id_idx");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Blackout", b =>
                {
                    b.Property<byte[]>("BlackoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("blackout_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.HasKey("BlackoutId");

                    b.HasIndex(new[] { "BlackoutId" }, "blackout_id_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "ResidentId" }, "resident_id_blackouts_idx");

                    b.ToTable("blackouts", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Date", b =>
                {
                    b.Property<byte[]>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("date_id");

                    b.Property<int>("CallType")
                        .HasColumnType("int")
                        .HasColumnName("call_type");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("hours");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<byte[]>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("schedule_id");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("DateId");

                    b.HasIndex(new[] { "ResidentId" }, "resident_id_dates_idx");

                    b.HasIndex(new[] { "ScheduleId" }, "schedule_id");

                    b.HasIndex(new[] { "DateId" }, "schedule_id_UNIQUE")
                        .IsUnique();

                    b.ToTable("dates", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Invitation", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("datetime")
                        .HasColumnName("expires");

                    b.Property<string>("ResidentId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resident_id");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("used");

                    b.HasKey("Token")
                        .HasName("PRIMARY");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.PGY4RotationSchedule", b =>
                {
                    b.Property<byte[]>("PGY4RotationScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("pgy4_rotation_schedule_id");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("seed");

                    b.HasKey("PGY4RotationScheduleId");

                    b.ToTable("pgy4_rotation_schedule");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Resident", b =>
                {
                    b.Property<string>("ResidentId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<int>("BiYearlyHours")
                        .HasColumnType("int")
                        .HasColumnName("bi_yearly_hours");

                    b.Property<int>("ChiefType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("first_name");

                    b.Property<int>("GraduateYr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("graduate_yr")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("HospitalRoleProfile")
                        .HasColumnType("int")
                        .HasColumnName("hospital_role_profile");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password")
                        .HasDefaultValueSql("''");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_num")
                        .HasDefaultValueSql("''");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int")
                        .HasColumnName("total_hours");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("int")
                        .HasColumnName("weekly_hours");

                    b.HasKey("ResidentId");

                    b.HasIndex(new[] { "Email" }, "email_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "ResidentId" }, "resident_id_UNIQUE")
                        .IsUnique();

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Rotation", b =>
                {
                    b.Property<byte[]>("RotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("rotation_id");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("month");

                    b.Property<int>("MonthIndex")
                        .HasColumnType("int");

                    b.Property<byte[]>("Pgy4RotationScheduleId")
                        .HasColumnType("binary(16)");

                    b.Property<int>("PgyYear")
                        .HasColumnType("int");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<string>("Rotation1")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("rotation");

                    b.Property<byte[]>("RotationTypeId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("RotationId");

                    b.HasIndex("RotationTypeId");

                    b.HasIndex(new[] { "ResidentId" }, "resident_id_rotation_idx");

                    b.HasIndex(new[] { "RotationId" }, "rotation_id_UNIQUE")
                        .IsUnique();

                    b.ToTable("rotations", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.RotationPrefRequest", b =>
                {
                    b.Property<byte[]>("RotationPrefRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("longtext")
                        .HasColumnName("additional_notes");

                    b.Property<byte[]>("EighthPriorityId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("eighth_priority_id");

                    b.Property<byte[]>("FifthPriorityId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("fifth_priority_id");

                    b.Property<byte[]>("FirstAlternativeId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("first_alternative_id");

                    b.Property<byte[]>("FirstAvoidId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("first_avoid_id");

                    b.Property<byte[]>("FirstPriorityId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("first_priority_id");

                    b.Property<byte[]>("FourthPriorityId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("fourth_priority_id");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<byte[]>("SecondAlternativeId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("second_alternative_id");

                    b.Property<byte[]>("SecondAvoidId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("second_avoid_id");

                    b.Property<byte[]>("SecondPriorityId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("second_priority_id");

                    b.Property<byte[]>("SeventhPriorityId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("seventh_priority_id");

                    b.Property<byte[]>("SixthPriorityId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("sixth_priority_id");

                    b.Property<byte[]>("ThirdAlternativeId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("third_alternative_id");

                    b.Property<byte[]>("ThirdAvoidId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("third_avoid_id");

                    b.Property<byte[]>("ThirdPriorityId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("third_priority_id");

                    b.HasKey("RotationPrefRequestId");

                    b.HasIndex("EighthPriorityId");

                    b.HasIndex("FifthPriorityId");

                    b.HasIndex("FirstAlternativeId");

                    b.HasIndex("FirstAvoidId");

                    b.HasIndex("FirstPriorityId");

                    b.HasIndex("FourthPriorityId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SecondAlternativeId");

                    b.HasIndex("SecondAvoidId");

                    b.HasIndex("SecondPriorityId");

                    b.HasIndex("SeventhPriorityId");

                    b.HasIndex("SixthPriorityId");

                    b.HasIndex("ThirdAlternativeId");

                    b.HasIndex("ThirdAvoidId");

                    b.HasIndex("ThirdPriorityId");

                    b.ToTable("rotation_pref_request");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.RotationType", b =>
                {
                    b.Property<byte[]>("RotationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("rotation_type_id");

                    b.Property<bool>("DoesLongCall")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("does_long_call");

                    b.Property<bool>("DoesShortCall")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("does_short_call");

                    b.Property<bool>("DoesTrainingLongCall")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("does_training_long_call");

                    b.Property<bool>("DoesTrainingShortCall")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("does_training_short_call");

                    b.Property<bool>("IsChiefRotation")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_chief_rotation");

                    b.Property<int>("PgyYearFlags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("pgy_year_flags");

                    b.Property<string>("RotationName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rotation_name");

                    b.HasKey("RotationTypeId");

                    b.ToTable("rotation_type");

                    b.HasData(
                        new
                        {
                            RotationTypeId = new byte[] { 163, 198, 184, 245, 23, 100, 68, 75, 189, 163, 202, 94, 123, 238, 8, 109 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 15,
                            RotationName = "Unassigned"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 43, 16, 19, 7, 193, 3, 98, 74, 191, 216, 76, 4, 54, 154, 199, 196 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 15,
                            RotationName = "Inpatient Psy"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 234, 143, 171, 248, 255, 175, 221, 70, 174, 199, 66, 61, 121, 28, 232, 209 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "Geriatric"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 165, 18, 107, 68, 24, 126, 253, 72, 138, 187, 32, 211, 154, 90, 163, 83 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "PHPandIOP"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 215, 87, 101, 160, 153, 16, 236, 66, 156, 238, 237, 62, 236, 98, 19, 171 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 15,
                            RotationName = "Psy Consults"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 110, 22, 50, 137, 36, 220, 60, 79, 136, 215, 63, 185, 238, 126, 22, 26 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 15,
                            RotationName = "Community Psy"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 209, 143, 230, 137, 204, 40, 127, 77, 176, 253, 32, 254, 216, 57, 98, 49 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "CAP"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 215, 39, 22, 119, 159, 186, 73, 69, 137, 138, 66, 103, 253, 20, 228, 58 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 15,
                            RotationName = "Addiction"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 44, 1, 68, 181, 224, 204, 217, 73, 178, 214, 31, 23, 6, 141, 183, 210 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 15,
                            RotationName = "Forensic"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 146, 142, 124, 165, 250, 119, 15, 65, 190, 84, 145, 38, 136, 28, 53, 20 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "Float"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 219, 221, 77, 165, 69, 2, 130, 69, 135, 54, 87, 227, 13, 138, 12, 23 },
                            DoesLongCall = false,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "Neurology"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 88, 181, 70, 110, 90, 85, 4, 68, 129, 85, 19, 29, 197, 159, 164, 48 },
                            DoesLongCall = false,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "ImOutpatient"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 127, 107, 64, 16, 183, 28, 13, 77, 177, 78, 121, 131, 164, 140, 28, 232 },
                            DoesLongCall = false,
                            DoesShortCall = false,
                            DoesTrainingLongCall = false,
                            DoesTrainingShortCall = false,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "ImInpatient"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 198, 128, 90, 38, 155, 98, 143, 70, 131, 234, 116, 101, 192, 246, 51, 195 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "NightFloat"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 81, 121, 28, 144, 20, 87, 143, 72, 151, 49, 99, 107, 225, 251, 106, 236 },
                            DoesLongCall = false,
                            DoesShortCall = false,
                            DoesTrainingLongCall = false,
                            DoesTrainingShortCall = false,
                            IsChiefRotation = false,
                            PgyYearFlags = 7,
                            RotationName = "EmergencyMed"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 78, 40, 245, 224, 213, 0, 234, 76, 186, 46, 163, 113, 141, 91, 112, 196 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = true,
                            PgyYearFlags = 8,
                            RotationName = "Chief"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 16, 45, 246, 231, 218, 87, 73, 71, 156, 16, 11, 78, 197, 56, 160, 71 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 8,
                            RotationName = "TMS"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 191, 177, 71, 69, 124, 87, 217, 74, 130, 70, 127, 8, 94, 217, 87, 249 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 8,
                            RotationName = "IOP"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 50, 124, 227, 176, 25, 121, 82, 77, 191, 32, 242, 114, 201, 138, 78, 131 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 8,
                            RotationName = "NFETC"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 65, 201, 67, 126, 192, 225, 88, 76, 143, 65, 83, 94, 26, 26, 130, 219 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 8,
                            RotationName = "HPC"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 217, 68, 77, 152, 241, 47, 25, 73, 168, 149, 204, 134, 90, 158, 72, 114 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 8,
                            RotationName = "VA"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 41, 63, 243, 128, 169, 207, 66, 68, 180, 88, 117, 40, 90, 217, 147, 196 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 8,
                            RotationName = "CLC"
                        },
                        new
                        {
                            RotationTypeId = new byte[] { 129, 242, 99, 144, 25, 121, 55, 73, 180, 107, 234, 4, 20, 112, 24, 202 },
                            DoesLongCall = true,
                            DoesShortCall = true,
                            DoesTrainingLongCall = true,
                            DoesTrainingShortCall = true,
                            IsChiefRotation = false,
                            PgyYearFlags = 8,
                            RotationName = "Sum"
                        });
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Schedule", b =>
                {
                    b.Property<byte[]>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("schedule_id");

                    b.Property<int>("GeneratedYear")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ScheduleId");

                    b.HasIndex(new[] { "ScheduleId" }, "schedule_id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("schedule_id_UNIQUE1");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.SwapRequest", b =>
                {
                    b.Property<byte[]>("SwapRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("idswap_requests");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Details")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("details");

                    b.Property<DateOnly>("RequesteeDate")
                        .HasColumnType("date")
                        .HasColumnName("requestee_date");

                    b.Property<string>("RequesteeId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("requestee_id");

                    b.Property<DateOnly>("RequesterDate")
                        .HasColumnType("date")
                        .HasColumnName("requester_date");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("requester_id");

                    b.Property<byte[]>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("schedule_swap_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SwapRequestId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SwapRequestId" }, "idswap_requests_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "RequesteeId" }, "requestee_id_idx");

                    b.HasIndex(new[] { "RequesterId" }, "requester_id_idx");

                    b.HasIndex(new[] { "ScheduleId" }, "schedule_id_idx");

                    b.ToTable("swap_requests", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Vacation", b =>
                {
                    b.Property<byte[]>("VacationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("vacation_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Details")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("details");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("groupId");

                    b.Property<string>("HalfDay")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("half_day")
                        .IsFixedLength();

                    b.Property<string>("Reason")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("reason");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("resident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.HasKey("VacationId");

                    b.HasIndex(new[] { "ResidentId" }, "idx_resident_id");

                    b.ToTable("vacations", (string)null);
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Announcement", b =>
                {
                    b.HasOne("MedicalDemo.Models.Entities.Admin", "Author")
                        .WithMany("Announcements")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Blackout", b =>
                {
                    b.HasOne("MedicalDemo.Models.Entities.Resident", "Resident")
                        .WithMany("Blackouts")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resident_id_blackouts");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Date", b =>
                {
                    b.HasOne("MedicalDemo.Models.Entities.Resident", "Resident")
                        .WithMany("Dates")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resident_id_dates");

                    b.HasOne("MedicalDemo.Models.Entities.Schedule", "Schedule")
                        .WithMany("Dates")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("schedule_id");

                    b.Navigation("Resident");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Rotation", b =>
                {
                    b.HasOne("MedicalDemo.Models.Entities.Resident", "Resident")
                        .WithMany("Rotations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resident_id_rotation");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "RotationType")
                        .WithMany()
                        .HasForeignKey("RotationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("RotationType");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.RotationPrefRequest", b =>
                {
                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "EighthPriority")
                        .WithMany()
                        .HasForeignKey("EighthPriorityId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "FifthPriority")
                        .WithMany()
                        .HasForeignKey("FifthPriorityId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "FirstAlternative")
                        .WithMany()
                        .HasForeignKey("FirstAlternativeId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "FirstAvoid")
                        .WithMany()
                        .HasForeignKey("FirstAvoidId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "FirstPriority")
                        .WithMany()
                        .HasForeignKey("FirstPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "FourthPriority")
                        .WithMany()
                        .HasForeignKey("FourthPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalDemo.Models.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "SecondAlternative")
                        .WithMany()
                        .HasForeignKey("SecondAlternativeId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "SecondAvoid")
                        .WithMany()
                        .HasForeignKey("SecondAvoidId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "SecondPriority")
                        .WithMany()
                        .HasForeignKey("SecondPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "SeventhPriority")
                        .WithMany()
                        .HasForeignKey("SeventhPriorityId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "SixthPriority")
                        .WithMany()
                        .HasForeignKey("SixthPriorityId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "ThirdAlternative")
                        .WithMany()
                        .HasForeignKey("ThirdAlternativeId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "ThirdAvoid")
                        .WithMany()
                        .HasForeignKey("ThirdAvoidId");

                    b.HasOne("MedicalDemo.Models.Entities.RotationType", "ThirdPriority")
                        .WithMany()
                        .HasForeignKey("ThirdPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EighthPriority");

                    b.Navigation("FifthPriority");

                    b.Navigation("FirstAlternative");

                    b.Navigation("FirstAvoid");

                    b.Navigation("FirstPriority");

                    b.Navigation("FourthPriority");

                    b.Navigation("Resident");

                    b.Navigation("SecondAlternative");

                    b.Navigation("SecondAvoid");

                    b.Navigation("SecondPriority");

                    b.Navigation("SeventhPriority");

                    b.Navigation("SixthPriority");

                    b.Navigation("ThirdAlternative");

                    b.Navigation("ThirdAvoid");

                    b.Navigation("ThirdPriority");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.SwapRequest", b =>
                {
                    b.HasOne("MedicalDemo.Models.Entities.Resident", "Requestee")
                        .WithMany("SwapRequestRequestees")
                        .HasForeignKey("RequesteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("requestee_id");

                    b.HasOne("MedicalDemo.Models.Entities.Resident", "Requester")
                        .WithMany("SwapRequestRequesters")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("requester_id");

                    b.HasOne("MedicalDemo.Models.Entities.Schedule", "ScheduleSwap")
                        .WithMany("SwapRequests")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("schedule_swap_id");

                    b.Navigation("Requestee");

                    b.Navigation("Requester");

                    b.Navigation("ScheduleSwap");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Vacation", b =>
                {
                    b.HasOne("MedicalDemo.Models.Entities.Resident", "Resident")
                        .WithMany("Vacations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resident_id_vacations");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Admin", b =>
                {
                    b.Navigation("Announcements");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Resident", b =>
                {
                    b.Navigation("Blackouts");

                    b.Navigation("Dates");

                    b.Navigation("Rotations");

                    b.Navigation("SwapRequestRequestees");

                    b.Navigation("SwapRequestRequesters");

                    b.Navigation("Vacations");
                });

            modelBuilder.Entity("MedicalDemo.Models.Entities.Schedule", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("SwapRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
